### ISSUE TITLE
in-memory cache couldn't pass test

### ISSUE THREAD

**Issue by xialingxiao** [goenning/go-cache-demo#2]
```
$ go test $(go list ./... | grep -v /vendor/) -cover
?   	go-cache-demo	[no test files]
?   	go-cache-demo/cache	[no test files]
ok  	go-cache-demo/cache/memory	1.016s	coverage: 0.0% of statements
--- FAIL: TestGetValue (0.00s)
	cache_test.go:52: content should '123456', but was ''
FAIL
coverage: 0.0% of statements
FAIL	go-cache-demo/cache/redis	1.024s
$ go version
go version go1.8.1 darwin/amd64
```

**Comment by goenning** [comment]
hey @xialingxiao, can you pull and try again?
I've increased the sleep time by 200ms just to be sure the key would be expired.

**Comment by xialingxiao** [comment]
hmm, but the failed test is for `TestGetValue`, you increased it for `TestGetExpiredValue `.

**Comment by goenning** [comment]
Ohh, what's failing is the tests inside redis package, right? You need a redis instance to run those tests. If you have docker, just run `docker-compose up -d`

**Comment by xialingxiao** [comment]
my bad, sorry didn't notice that
